# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/powerplatform-actions/pack-solution@v0
        with: 
          solution-file: packed-solutions/pi_core.zip
          solution-folder: solutions/pi_core/src
          solution-type: Both
      - uses: actions/upload-artifact@v2
        with: 
          name: packed-solutions
          path: packed-solutions
     
